### ISSUE TITLE
What adaptations I need to make to use the FOMOH on a Transformers-based model.？

### ISSUE THREAD

**Issue by laujianmin** [SRI-CSL/fomoh#1]
Hi~ Thank you very much for open sourcing this great project!

 I apologize for not being very proficient in code migration. 
I would like to know what adaptations I need to make to use the FOMOH optimization algorithm on a model architecture based on Transformers. Do I need to redefine the Hugging Face model interface? 

I hope to receive your reply and am very grateful.

**Comment by AdamCobb** [comment]
Hi! 

Thanks for your interest! At the moment, Fomoh does not have a Transformer-based architecture. If I get time, I might be able to implement it myself, otherwise feel free to contribute.

All the best,

Adam
